name: tests

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        python: [3.6, 3.8, 3.9]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install tox
        run: |
          python -m pip install tox
      - name: Run tests
        run: tox

  test_msys2_mingw:
    strategy:
      matrix:
        include:
          - { sys: mingw64, env: x86_64 }
          - { sys: mingw32, env: i686 }
          - { sys: ucrt64,  env: ucrt-x86_64 }
          - { sys: clang64, env: clang-x86_64 }
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: msys2/setup-msys2@v2
        with:
          msystem: ${{matrix.sys}}
          install: |
            mingw-w64-${{matrix.env}}-python
            mingw-w64-${{matrix.env}}-python-tox
      - name: Run tests
        run: tox

  ci_setuptools:
    # Integration testing with setuptools
    strategy:
      matrix:
        python: [3.9]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    env:
      SETUPTOOLS_USE_DISTUTILS: local
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install tox
        run: |
          python -m pip install tox
      - name: Check out pypa/setuptools
        uses: actions/checkout@v2
        with:
          repository: pypa/setuptools
          ref: main
          path: integration/setuptools
      - name: Replace vendored distutils
        run: |
          cd integration/setuptools/setuptools
          rm -rf _distutils
          cp -rp ../../../distutils _distutils
      - name: Run setuptools tests
        run: |
          cd integration/setuptools
          tox

  release:
    needs: test
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install tox
        run: |
          python -m pip install tox
      - name: Release
        run: tox -e release
        env:
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

